config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  root 'home#index'
  get 'home/index'
  get 'home/contact', as: 'contact'
  get 'home/login', as: 'login'
  get 'home/payment', as: 'payment'
  get 'home/product', as: 'product'
=======
  devise_for :users
  root 'home#index'
  get 'home/private'
>>>>>>> dev
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :sanitize_devise_params, if: :devise_controller?
def sanitize_devise_params
	devise_parameter_sanitizer.permit(:sign_up, keys: [:address] )
	
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

<<<<<<< HEAD
  def contact
  end

  def login
  end

  def payment
  end

  def product
=======
  def private
>>>>>>> dev
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<<<<<<< HEAD
<div class="jumbotron">
  <h1 class="display-3">Hello, guys! Kitty lovers??</h1>
  <p class="lead">This site was made for you... Here, you will be able to have kitty's pics or the best of all, a cat, of any breed you like.</p>
  <hr class="my-4">
  <p>"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="<%= login_path %>" role="button">Go shopping</a>
  </p>
</div>

<div class="site-content">
    <div class="row">
        <div class="col-lg-3">
            <%= image_tag "i2.png", class: "image-test" %>
        </div>
        <div class="col-lg-3">
            <p> <b>Lorem ipsum</b> dolor sit amet, consectetur adipisicing elit. Repudiandae illum, libero laudantium provident. Velit et tenetur temporibus aperiam repudiandae voluptatibus maxime suscipit quisquam, doloremque perferendis. Delectus ad fuga deleniti pariatur!</p> 
              <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae illum, libero laudantium provident. Velit et tenetur temporibus aperiam repudiandae voluptatibus maxime suscipit quisquam, doloremque perferendis. Delectus ad fuga deleniti pariatur!</p>
              <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae illum, libero laudantium provident. Velit et tenetur temporibus aperiam repudiandae voluptatibus maxime suscipit quisquam, doloremque perferendis. Delectus ad fuga deleniti pariatur!</p> 
              <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae illum, libero laudantium provident. Velit et tenetur temporibus aperiam repudiandae voluptatibus maxime suscipit quisquam, doloremque perferendis. Delectus ad fuga deleniti pariatur!</p> 	 	
        </div>
        <div class="col-lg-3">
            <%= image_tag "i4.png", class: "image-test" %> 	 	
        </div>
        <div class="col-lg-3">
            <p> <b>Lorem ipsum</b> dolor sit amet, consectetur adipisicing elit. Repudiandae illum, libero laudantium provident. Velit et tenetur temporibus aperiam repudiandae voluptatibus maxime suscipit quisquam, doloremque perferendis. Delectus ad fuga deleniti pariatur!</p> 
              <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae illum, libero laudantium provident. Velit et tenetur temporibus aperiam repudiandae voluptatibus maxime suscipit quisquam, doloremque perferendis. Delectus ad fuga deleniti pariatur!</p>
              <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae illum, libero laudantium provident. Velit et tenetur temporibus aperiam repudiandae voluptatibus maxime suscipit quisquam, doloremque perferendis. Delectus ad fuga deleniti pariatur!</p> 
              <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae illum, libero laudantium provident. Velit et tenetur temporibus aperiam repudiandae voluptatibus maxime suscipit quisquam, doloremque perferendis. Delectus ad fuga deleniti pariatur!</p> 	 	
        </div>
</div>

<!-- test -->

<div class="team">
<h1 align="center">La Team</h1>
<div class="row">
    <div class="col-lg-3">
        <div class="our-team">
            <%= image_tag "header-bg.png", class: "card" %>
            <h5>Andee Rakut</h5>
            <h6>Designer/Front-end Developer</h6>
            <div class="wrapper">
                <a target="_blank" href="your_url_here"><i class="fa fa-3x fa-linkedin-square"></i></a>
                <a target="_blank" href="your_url_here"><i class="fa fa-3x fa-facebook-square"></i></a>
                <a target="_blank" href="your_url_here"><i class="fa fa-3x fa-twitter-square"></i>
             </div></a>
            
        </div>
    </div>
    <div class="col-lg-3">
        <div class="our-team">
            <%= image_tag "i1.png", class: "card" %>
            <h5>Lantoniaina</h5>
            <h6>Web Designer</h6>
            <div class="wrapper">
                <a target="_blank" href="your_url_here"><i class="fa fa-3x fa-linkedin-square"></i></a>
                <a target="_blank" href="your_url_here"><i class="fa fa-3x fa-facebook-square"></i></a>
                <a target="_blank" href="your_url_here"><i class="fa fa-3x fa-twitter-square"></i>
             </div></a>
            
        </div>		
    </div>
    <div class="col-lg-3">
    <div class="our-team">
        <%= image_tag "i2.png", class: "card" %>
        <h5>Andy Ral</h5>
        <h6>Backend Developer</h6>
        <div class="wrapper">
            <a target="_blank" href="your_url_here"><i class="fa fa-3x fa-linkedin-square"></i></a>
            <a target="_blank" href="your_url_here"><i class="fa fa-3x fa-facebook-square"></i></a>
            <a target="_blank" href="your_url_here"><i class="fa fa-3x fa-twitter-square"></i>
         </div></a>
        
    </div>		
</div>
    <div class="col-lg-3">
        <div class="our-team">
            <%= image_tag "i6.png", class: "card" %>
        <h5>Mahefa</h5>
       <h6>Backend Developer</h6>
       <div class="wrapper">
        <a target="_blank" href="your_url_here"><i class="fa fa-3x fa-linkedin-square"></i></a>
        <a target="_blank" href="your_url_here"><i class="fa fa-3x fa-facebook-square"></i></a>
        <a target="_blank" href="your_url_here"><i class="fa fa-3x fa-twitter-square"></i>
     </div></a>
        </div>		
    </div>
    </div>
</div>
</div>


=======
<ul>
	<% if  user_signed_in? %>
    <li>
    	<%=  link_to 'Déconnexion', destroy_user_session_path, method: :delete %>
    </li>
    <li>
    	<%= current_user.email %>
    </li>
    <li>
    	<%= link_to "Modifier Profil", edit_user_registration_path %>
    </li>
    <% else %>
    <li>
    	<%= link_to 'Connexion', new_user_session_path %>
    </li>
    <li>
    	<%= link_to 'Insscription', new_user_registration_path %>
    </li>
   
	<% end %>
</ul>



<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
>>>>>>> dev

app/views/home/login.html.erb
<h1>Home#login</h1>
<p>Find me in app/views/home/login.html.erb</p>

app/views/home/payment.html.erb
<h1>Home#payment</h1>
<p>Find me in app/views/home/payment.html.erb</p>

app/views/home/private.html.erb
<h1>Home#private</h1>
<p>Find me in app/views/home/private.html.erb</p>

app/views/home/product.html.erb
<h1>Home#product</h1>
<p>Find me in app/views/home/product.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>eCommerce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="css/_variable.scss">
    <link rel="stylesheet" href="css/_bootswatch.scss"> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">e-commerce</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor03">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= product_path %>">Product</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= payment_path %>">Checkout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= contact_path %>">Contact</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= login_path %>">Account</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

    <%= yield %>
  </body>
</html>